from __future__ import annotations

import tempfile
from pathlib import Path
from threading import Thread

import gradio as gr
from PIL import Image, ImageDraw, ImageFont, ImageOps
from transformers import TextIteratorStreamer

# Official HunyuanOCR task-type prompts (mirrors the task presets in the
# tencent/HunyuanOCR Space and the `--task-type` options of the shipped
# vLLM/transformers clients). Selecting a preset only fills the editable
# prompt box below — you can always type a free-form instruction instead.
TASK_PROMPTS: dict[str, str] = {
    "Document parsing": (
        "Extract all the body text from the document image in markdown format. "
        "Ignore headers and footers, express tables in HTML format and formulas "
        "in LaTeX format, and organize the output in reading order."
    ),
    "Text spotting": "Detect and recognize the text in the image, and output the text with its coordinates.",
    "Information extraction": "Extract all the key field contents from the image and return them in JSON format.",
    "Visual QA": "Please describe the content of the image.",
    "Translate to Chinese": "Translate the text in the image into Chinese.",
    "Translate to English": "Translate the text in the image into English.",
}

DEFAULT_PROMPT = TASK_PROMPTS["Document parsing"]

# Name of the synthetic sample document generated by :func:`make_sample_image`.
SAMPLE_IMAGE = "hunyuan_ocr_sample.png"


def _load_font(size: int):
    """Best-effort load of a TrueType font, falling back to PIL's bitmap font."""
    for name in ("arial.ttf", "DejaVuSans.ttf", "LiberationSans-Regular.ttf"):
        try:
            return ImageFont.truetype(name, size)
        except OSError:
            continue
    return ImageFont.load_default()


def make_sample_image(path: str | Path = SAMPLE_IMAGE) -> Path:
    """Render a small synthetic document image for the demo.

    No binary asset is shipped with the notebook; the sample is drawn on the
    fly so the notebook is fully self-contained and reproducible. The page
    contains a title, a couple of text paragraphs and a tiny table so the
    document-parsing prompt has structure to recognise.
    """
    path = Path(path)
    if path.exists():
        return path

    W, H = 960, 640
    img = Image.new("RGB", (W, H), "white")
    draw = ImageDraw.Draw(img)

    title_font = _load_font(34)
    head_font = _load_font(24)
    body_font = _load_font(20)

    draw.text((60, 40), "OpenVINO Quarterly Report", font=title_font, fill="black")
    draw.line((60, 90, W - 60, 90), fill="black", width=2)

    paragraph = [
        "HunyuanOCR is a lightweight end-to-end OCR vision-language model.",
        "This tutorial converts it to the OpenVINO Intermediate Representation",
        "and runs inference on Intel CPU and GPU through optimum-intel.",
    ]
    y = 120
    for line in paragraph:
        draw.text((60, y), line, font=body_font, fill="black")
        y += 34

    draw.text((60, 250), "Revenue by Quarter", font=head_font, fill="black")

    # Simple 3-column table.
    rows = [
        ["Quarter", "Revenue", "Growth"],
        ["Q1 2026", "$1.20M", "+5%"],
        ["Q2 2026", "$1.45M", "+21%"],
        ["Q3 2026", "$1.72M", "+19%"],
    ]
    x0, y0 = 60, 300
    col_w, row_h = 260, 44
    for r, row in enumerate(rows):
        for c, cell in enumerate(row):
            x, y = x0 + c * col_w, y0 + r * row_h
            draw.rectangle((x, y, x + col_w, y + row_h), outline="black", width=1)
            draw.text((x + 12, y + 10), cell, font=body_font, fill="black")

    draw.text((60, 520), "Contact: reports@openvino.example", font=body_font, fill="black")

    img.save(path, format="PNG")
    return path


def _build_inputs(processor, image: Image.Image, prompt: str):
    """Build model inputs, aligned with the HunyuanOCR native transformers usage."""
    image = ImageOps.exif_transpose(image.convert("RGB"))
    tmp = tempfile.NamedTemporaryFile(suffix=".png", delete=False)
    image.save(tmp.name, format="PNG")
    tmp.close()
    messages = [
        {
            "role": "user",
            "content": [
                {"type": "image", "image": tmp.name},
                {"type": "text", "text": prompt},
            ],
        }
    ]
    inputs = processor.apply_chat_template(
        messages,
        tokenize=True,
        add_generation_prompt=True,
        return_dict=True,
        return_tensors="pt",
    )
    return inputs


def _result_textbox(label: str, lines: int = 24):
    import inspect as _inspect

    kw = {"label": label, "lines": lines}
    params = _inspect.signature(gr.Textbox).parameters
    if "show_copy_button" in params:
        kw["show_copy_button"] = True
    if "autoscroll" in params:
        kw["autoscroll"] = True
    return gr.Textbox(**kw)


def make_demo(model, processor):
    """Build a single-image Gradio demo for HunyuanOCR on OpenVINO.

    Upload an image, optionally pick a task preset to fill the prompt (or type
    your own free-form instruction), and watch the decoded text stream in.
    """
    tokenizer = processor.tokenizer if hasattr(processor, "tokenizer") else processor

    def run(image, prompt, max_new_tokens):
        if image is None:
            yield "[ERROR] Please upload an image first."
            return
        if not prompt or not prompt.strip():
            prompt = DEFAULT_PROMPT
        inputs = _build_inputs(processor, image, prompt)
        streamer = TextIteratorStreamer(tokenizer, skip_prompt=True, skip_special_tokens=True)
        gen_kwargs = dict(
            inputs,
            max_new_tokens=int(max_new_tokens),
            do_sample=False,
            streamer=streamer,
        )
        thread = Thread(target=model.generate, kwargs=gen_kwargs, daemon=True)
        thread.start()
        buf = ""
        for piece in streamer:
            buf += piece
            yield buf
        thread.join(timeout=1.0)

    def fill_prompt(task):
        return TASK_PROMPTS.get(task, DEFAULT_PROMPT)

    with gr.Blocks(title="HunyuanOCR + OpenVINO") as demo:
        gr.Markdown(
            "# HunyuanOCR + OpenVINO\n"
            "Upload an image and run [HunyuanOCR](https://huggingface.co/tencent/HunyuanOCR) "
            "through optimum-intel + OpenVINO. Pick a task preset to fill the prompt, "
            "or type your own instruction."
        )
        with gr.Row():
            with gr.Column(scale=1):
                image_in = gr.Image(type="pil", label="Image")
                task = gr.Dropdown(
                    choices=list(TASK_PROMPTS.keys()),
                    value="Document parsing",
                    label="Task preset (fills the prompt below)",
                )
                prompt = gr.Textbox(value=DEFAULT_PROMPT, lines=3, label="Prompt")
                max_toks = gr.Slider(
                    minimum=64,
                    maximum=8192,
                    value=2048,
                    step=64,
                    label="max_new_tokens",
                )
                run_btn = gr.Button("Run", variant="primary")
            with gr.Column(scale=1):
                output = _result_textbox("Result")

        task.change(fill_prompt, inputs=task, outputs=prompt)
        run_btn.click(run, inputs=[image_in, prompt, max_toks], outputs=output)

        sample = Path(SAMPLE_IMAGE)
        if sample.exists():
            gr.Examples(
                examples=[[str(sample), DEFAULT_PROMPT, 2048]],
                inputs=[image_in, prompt, max_toks],
                label="Examples",
            )

    return demo
