name: codequality

# Flake8 tests:
# E111 indentiation not multiple of four
# E261 at least two spaces before comment
# E303 too many blank lines
# F401 imported but unused
# F811 redefinition

on:
  workflow_dispatch:
  pull_request:
    branches:
    - 'main'
    paths:
    - 'notebooks/**.ipynb'
    - 'notebooks/**.py'
    - 'requirements.txt'
    - '.ci/*'
    - '.github/workflows/codequality.yml'
  push:
    branches:
    - 'main'
    paths:
    - 'notebooks/**.ipynb'
    - 'notebooks/**.py'
    - 'requirements.txt'
    - '.ci/*'
    - '.github/workflows/codequality.yml'
    

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r .ci/dev-requirements.txt
        python -m ipykernel install --user --name openvino_env
    - name: Flake8
      run: |
        nbqa flake8 --ignore=E124,E203,E266,E402,E501,F821,W503,W291,W293 --nbqa-exclude="(30.*)|(208.*)" notebooks
    - name: Check READMEs
      run: |
        python -m pytest .ci/test_notebooks.py
