name: create_utils

on: 
  push:
    paths:
      - 'notebooks/utils/notebook_utils.ipynb'
  pull_request:
    paths:
      - 'notebooks/utils/notebook_utils.ipynb'

jobs:
  build:
    strategy:
      fail-fast: false

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install openvino-dev jupyterlab nbval
        python -m ipykernel install --user --name openvino_env
    - name: Create notebook_utils.py
      run: |
        jupyter nbconvert notebooks/utils/notebook_utils.ipynb --TagRemovePreprocessor.remove_cell_tags='{"hide"}' --to script
    - name: Create PR
      uses: peter-evans/create-pull-request@v3
      with:
        commit-message: 'CI: Generate notebook_utils.py'
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: ci-create-utils
        delete-branch: true
        title: 'CI: Create notebook_utils.py'

