name: install_requirements_china

on:
  workflow_dispatch:
  schedule:
    - cron: '30 18 * * *'

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04]
        python: [3.9]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip==21.3.* -i https://pypi.tuna.tsinghua.edu.cn/simple
          python -m pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

          python -m ipykernel install --user --name openvino_env
          python -m pip freeze > pip-freeze-${{ github.sha }}-${{matrix.os}}-${{ matrix.python }}.txt
      - name: Archive pip freeze
        uses: actions/upload-artifact@65462800fd760344b1a7b4382951275a0abb4808 # v4.3.3
        with:
          name: pip-freeze-${{matrix.os}}-${{ matrix.python }}
          path: pip-freeze-${{ github.sha }}-${{matrix.os}}-${{ matrix.python }}.txt
      - name: Test that `jupyter lab` works
        run: |
          jupyter lab notebooks --help
      - name: Check install
        run: |
          python check_install.py
