name: pip_conflicts_check

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
      - 'latest'
    paths:
      - 'notebooks/**.ipynb'
  push:
    branches:
      - 'main'
      - 'latest'
    paths:
      - 'notebooks/**.ipynb'

permissions:
  contents: read

jobs:
  build_pip_conflicts_check:
    runs-on: ubuntu-20.04 # change cachepip step when changing this
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Dotenv Action
        id: dotenv
        uses: xom9ikk/dotenv@ac290ca23a42155a0cba1031d23afa46240116a9 # v2.3.0
        with:
          path: ./.github/workflows

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.9 # change cachepip step when changing this

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter "notebook<7"

      - name: Run pip conflicts check
        run: |
          bash .ci/pip_conflicts_check.sh --ignore .ci/ignore_pip_conflicts.txt
