name: Notebooks Selector Precommit

on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'latest'
    paths:
      - 'selector/**'
      - '.github/workflows/selector_precommit.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  link_build_selector:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 20

      - name: Install Node.js dependencies
        working-directory: ./selector
        shell: bash
        run: npm ci

      - name: Lint
        working-directory: ./selector
        shell: bash
        run: npm run lint

      - name: Build
        working-directory: ./selector
        shell: bash
        run: npm run build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
